### PR TITLE
Add rustfix WG

### PR DESCRIPTION
**Pull request by killercup**

### CODE REVIEW

**Comment by Manishearth** [comment]
https://github.com/rust-lang/team/blob/master/teams/devtools.toml#L19-L30 should be updated too

**Comment by Manishearth** [comment]
r=me with that change

**Comment by killercup** [comment]
Good catch! Updated

**Comment by Manishearth** [comment]
also, no lead?

**Comment by Manishearth** [comment]
Doesn't have to have one, but I assumed you were the lead of the team :)

**Comment by killercup** [comment]
Well, we haven't talked about having a leader. While I did lead the
meeting, I feel like we should at least discuss the topic before someone
(like me) takes over this team :D

**Comment by Manishearth** [comment]
Ah. r=me either way, @pietroalbini can you merge this?

**Pull request merged**
