### PR TITLE
Fix inconsistencies that slipped through the cracks

### PR DESCRIPTION
**Pull request by LEARAX**
I don't intend to spam this repository with shallow pull requests, but it looks like a few minor inconsistencies with the working groups were either introduced since I opened #127 or were simply overlooked. I believe I've fixed them now.

### CODE REVIEW

**Comment by LEARAX** [comment]
Some of my changes here are subjective; I thought that they made it seem more consistent/professional when looking at the site. If it's preferred that I revert them, let me know.

**Comment by Manishearth** [comment]
I don't think the working group names should be lower cased. The "Working Group" perhaps should be _uppercased_

**Comment by LEARAX** [comment]
> I don't think the working group names should be lower cased. The "Working Group" perhaps should be _uppercased_

Should the whole title be like that, then?

**Comment by Manishearth** [comment]
> Should the whole title be like that, then?

Yes

**Comment by nikomatsakis** [comment]
These do look like good changes -- I don't have a strong opinion about the capitalization of Working Group vs working group.

**Pull request closed without merging**
