### PR TITLE
shift pnkfelix to an alum on most of their team memberships.

### PR DESCRIPTION
**Pull request by pnkfelix**
I'm revising my approach to the Rust project, removing myself from most of the teams and shifting off of the maintainer role on the compiler team.

### CODE REVIEW

**Comment by weihanglo** [comment]
https://github.com/rust-lang/rust/commit/88bec09e6345d64d334c6dc1ef4947b35c467373 This is likely the earliest commit I could find.

Thank you Felix, for every contribution you made to the project and the community ❤️

**Comment by lqd** [comment]
Merci pour tout Felix <3

**Comment by jieyouxu** [comment]
Thanks for your contributions!

**Comment by apiraino** [comment]
:cry:

**Review by Mark-Simulacrum — APPROVED** [review]

**Pull request merged**
