### PR TITLE
Add m-ou-se to library-reviewers

### PR DESCRIPTION
**Pull request by dtolnay**
@m-ou-se expressed interest in helping with standard library reviews, and has already been doing a ton of terrific work on the standard library. :)

### CODE REVIEW

**Review by m-ou-se — APPROVED** [review]

**Comment by Mark-Simulacrum** [comment]
We should also update the highfive rotation probably.

**Comment by dtolnay** [comment]
https://github.com/rust-lang/highfive/pull/294

**Comment by m-ou-se** [comment]
Thanks!

This should've also added me to the github org(s), right? Looks like that didn't happen.

**Comment by pietroalbini** [comment]
Weird, started another synchronization manually.

**Comment by m-ou-se** [comment]
Thanks! Got the invitation now.

Not sure how this all works, but I think this new `library-reviewers` team still needs to be added to repositories?

**Comment by pietroalbini** [comment]
Yep. If someone from the libs team gives me a list of repositories I can do the change.

**Comment by dtolnay** [comment]
@pietroalbini: let's do *Write* permission on the following:

- https://github.com/rust-lang/backtrace-rs
- https://github.com/rust-lang/compiler-builtins
- https://github.com/rust-lang/getopts
- https://github.com/rust-lang/hashbrown
- https://github.com/rust-lang/libc
- https://github.com/rust-lang/packed_simd
- https://github.com/rust-lang/rust
- https://github.com/rust-lang/stdarch
- https://github.com/rust-lang/stdsimd

**Comment by pietroalbini** [comment]
@rust-lang/library-reviewers should've added write privileges to all the repositories listed above to y'all. This might've subscribed you to the `rust-lang/rust` repository: for your inbox's sake don't forget to unwatch that repository.

**Pull request merged**
