### PR TITLE
Update wg-traits team

### PR DESCRIPTION
**Pull request by jackh726**

### CODE REVIEW

**Comment by jackh726** [comment]
So not sure why CI is failing here. wg-traits doesn't have any mailing lists

**Comment by nikomatsakis** [comment]
That does seem curious. Maybe there is a mailing list of all WG devs? But then skinny121 was already a member... maybe @pietroalbini has an idea what's going on.

**Comment by jackh726** [comment]
My thought was maybe there's something special for alumni? But I couldn't find anything.

**Comment by pietroalbini** [comment]
Apparently they're added to the `all@` mailing list...

**Comment by pietroalbini** [comment]
Can we add the new members in this PR and move the past members to alumni in a separate PR? I don't want to block adding new members for too long.

**Comment by jackh726** [comment]
I updated to only add new people

**Pull request merged**
