### PR TITLE
Added embedded-resources subteam

### PR DESCRIPTION
**Pull request by therealprof**
Hopefully this satisfies the requirements of
https://github.com/rust-lang/rust/pull/64119

Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by pietroalbini** [comment]
You also need to add:

```toml
[github]
orgs = ["rust-lang"]
```

This will automatically synchronize the members of the team here with a GitHub team in the rust-lang organization. Everyone will be automatically invited by a bot a few minutes after the PR is merged.

**Comment by therealprof** [comment]
@pietroalbini Thanks for noticing that. I didn't see it by glancing over the other team definitions. I've updated the PR to include it.

**Comment by pietroalbini** [comment]
> I didn't see it by glancing over the other team definitions.

Yep, GitHub synchronization is relatively new and it hasn't been enabled for most of the team. We haven't enabled it everywhere mostly because some teams on GitHub are diverged from the data on the team repo, and team leads need to resolve the conflicts.

**Comment by pietroalbini** [comment]
Thanks! @adamgreig @andre-richter @jamesmunns @korken89 @ryankurte @thejpster @therealprof y'all should receive an invite to join the rust-lang organization soon. This is needed to be able to [assign you to embedded-book toolstate breakages](https://github.com/rust-lang/rust/pull/64119).

**Comment by andre-richter** [comment]
Worked 👍

**Pull request merged**
