### PR TITLE
Add Liwa Gu

### PR DESCRIPTION
**Pull request by albertlarsan68**
She is an OSPP mentee

cc @Kobzol

### CODE REVIEW

**Comment by albertlarsan68** [comment]
cc @rust-lang/team-repo-admins

**Review by rylev — CHANGES_REQUESTED** [review]
Adding a person without adding them to a team is rejected by CI because it doesn't actually do anything. Was the idea to add them to this? 

https://github.com/rust-lang/team/blob/16fc8a96bf2733bc0e7ca553a645f3840ed0a7a4/teams/ospp.toml#L6

**Comment by Kobzol** [comment]
They should be added to ospp-contributors, but it doesn't exist yet. It can be created in this PR I guess, as a copy paste of gsoc-contributors.

**Review by rylev — APPROVED** [review]

**Comment by tgross35** [comment]
@rylev OSPP is getting into its final ~month. Would this be able to merge so we could add the other mentees?

**Review by jackh726 — APPROVED** [review]

**Pull request merged**
