### PR TITLE
Add Secure Code WG

### PR DESCRIPTION
**Pull request by tarcieri**
Our charter can be found on our [coordination repo](https://github.com/rust-secure-code/wg#mission):

> Our mission is to make it easy to write secure code in Rust.
>
> We have the following goals for the Rust language and ecosystem:
>
> - Most tasks shouldn't require dangerous features such as unsafe. This includes FFI.
> - Mistakes in security code should be easily caught by machines or, failing that, humans aided by machines.
> - It should be clear to programmers how to perform security-sensitive tasks.
> - Security-critical code which is relied on by Rust programmers should be bug free.

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Seems good -- Are there more active people to include in the member list?

**Comment by tarcieri** [comment]
Yep. cc @alex @briansmith @devqps @RalfJung

**Comment by alex** [comment]
👋

**Comment by RalfJung** [comment]
I don't think I have time to load more WG memberships on my plate, but I hope the UCG WG and the Secure Code WG will closely work together where appropriate. :)

**Comment by tarcieri** [comment]
@RalfJung indeed, seems like a great collaboration so far

**Comment by nikomatsakis** [comment]
OK, well, I'm going to merge for now -- but you can always add more people in follow-up PRs. =)

**Comment by mikelodder7** [comment]
@tarcieri I would like to join this working group.

**Comment by tarcieri** [comment]
@mikelodder7 hi there! The best way to get started is probably to hop on our Zulip:

https://rust-lang.zulipchat.com/#narrow/stream/146229-wg-secure-code

**Pull request merged**
