### PR TITLE
Add web-presence-team repository under automation

### PR DESCRIPTION
**Pull request by Kobzol**
Repo: https://github.com/rust-lang/web-presence-team

Extracted from GH:
```toml
org = "rust-lang"
name = "web-presence-team"
description = "Home of the Web Presence Team"
bots = []

[access.teams]
security = "pull"

[access.individuals]
badboy = "admin"
rylev = "admin"
jdno = "admin"
pietroalbini = "admin"
Mark-Simulacrum = "admin"
rust-lang-owner = "admin"
```

### CODE REVIEW

**Review by rylev — APPROVED** [review]

**Comment by Kobzol** [comment]
The web-presence team doesn't even exist on GH, and the repo is 4 years old and has one commit. So I'm not sure if it's worth it to even create the team, or perhaps outright [remove the repo](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/Archiving.20unused.20rust-lang.20repos/near/417314589)?

**Comment by rylev** [comment]
It seems like there is only one thing that would be list be deleting the repo: https://github.com/rust-lang/web-presence-team/pull/1

Perhaps we can somehow archive that PR in some form?

**Comment by Kobzol** [comment]
Oh, I didn't notice that PR. Ok, in that case I would say "let's archive the whole repo" (in the future, once we're in the archiving phase, after the migration phase :laughing: ).

**Comment by rylev** [comment]
@Kobzol should we update this to archive the repo?

**Comment by Kobzol** [comment]
Actually, this should be closed, since this repo is already included in https://github.com/rust-lang/team/pull/1390.

**Pull request closed without merging**
