### PR TITLE
Grant myself try permissions

### PR DESCRIPTION
**Pull request by tgross35**
Some of my recent work has been flaky on certain platforms, and I would love to make use of the new `try-job`. Not sure what the rules for permissions are but it seems like maybe this is okay?

Also added perf because they are sometimes related (and I'm often online if others request a perf run). No specific need here though.

### CODE REVIEW

**Comment by DianQK** [comment]
I think wg-binary-size can be granted try and perf permissions.

**Comment by tgross35** [comment]
That works too, I only didn't propose it because the group is fairly inactive. @Kobzol any thoughts here?

**Comment by Kobzol** [comment]
Adding try and perf to wg-binary-size seems fine to me.

**Comment by tgross35** [comment]
That covers me, https://github.com/rust-lang/team/pull/1490

**Pull request closed without merging**
