### PR TITLE
make my vacation permanent

### PR DESCRIPTION
**Pull request by jyn514**
working on rust has not been healthy for me for a while. if i do work on it in the future, i want it to be because it's fun, not because i feel obligated, and having r+ permissions doesn't help with that.

### CODE REVIEW

**Comment by ozkanonur** [comment]
I really enjoyed working together with you. I hope we have the opportunity to work again in the future. Wish you best luck!

**Comment by Kobzol** [comment]
Thanks a lot for all your amazing work on Rust and your mentorship! <3 I wish you all the best.

**Comment by m-ou-se** [comment]
I'm sad to see you leave, but also very happy to see you're prioritizing health and enjoyment. <3 Thanks for everything. 💛

**Review by Mark-Simulacrum — APPROVED** [review]
Thank you!

**Pull request merged**
