### PR TITLE
Add some Arm engineers to the 'arm' team.

### PR DESCRIPTION
**Pull request by jacobbramley**

### CODE REVIEW

**Comment by pietroalbini** [comment]
Thanks for the PR! Can I get a confirmation from @hug-dev and @adamgemmell that they want to be added to the group of people pinged on Arm issues?

**Comment by hug-dev** [comment]
I confirm 😃!

**Comment by adamgemmell** [comment]
I can confirm this as well :)

**Comment by pietroalbini** [comment]
Great then!

**Comment by jacobbramley** [comment]
Thanks!

**Pull request merged**
