### PR TITLE
Add TaKO8Ki to compiler-contributors and wg-diagnostics

### PR DESCRIPTION
**Pull request by estebank**

### CODE REVIEW

**Comment by TaKO8Ki** [comment]
cc @wesleywiser @pnkfelix

**Comment by TaKO8Ki** [comment]
Could someone please review this? @rust-lang/core

**Comment by pnkfelix** [comment]
I'm 👍 on this.

**Review by Mark-Simulacrum — APPROVED** [review]

**Comment by TaKO8Ki** [comment]
I have not been added to the compiler-contributors team yet, did something happen during the synchronization?

**Comment by Mark-Simulacrum** [comment]
Should be fixed now. I think we have a bug where sometimes sync-team runs before caching invalidates across GitHub's CDN, which means we end up with a no-op run rather than actually taking action on the results.

cc @rylev -- we may want to adjust our CI here to either sleep for a minute or some other mitigation tactic, though this happens pretty rarely and clears up on the next run (which happens every day regardless).

**Pull request merged**
