### PR TITLE
Let myself queue perf runs

### PR DESCRIPTION
**Pull request by jyn514**
For https://github.com/rust-lang/rust/pull/73566

r? @Mark-Simulacrum

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
Hm don't you need try permissions as well?

**Comment by jyn514** [comment]
Good catch, added.

**Comment by jyn514** [comment]
Github is really not happy today ... I pushed changes but they're not showing up.

**Comment by Mark-Simulacrum** [comment]
Gah. I would really rather wait for CI here, so I'll do so. But this looks good to me.

**Pull request merged**
