### PR TITLE
Leave the Rustdoc team

### PR DESCRIPTION
**Pull request by jyn514**
I don't want to keep up with FCPs and I also don't want to block them (@Manishearth has suggested a few times that the minimum work required for being a member is "responding to FCPs in a timely manner").

Additionally, I don't want people to assign me on PRs.

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]
I'll be sad to see you go, hopefully we still see you around!

I will point out that the thing I mentioned about FCPs was largely for normal team members: I do think it's acceptable for team leads to focus on leadership and defer on FCPs/etc. But it does sound like you're not that interested in continuing, that's fine too. Feel free to reach out if you want to talk about it!

**Comment by GuillaumeGomez** [comment]
I'm sad that you're leaving us too... Thanks to you, rustdoc situation improved a lot. Hopefully, we will see you around.

**Comment by jsha** [comment]
Thanks for all you've done! You really helped me feel welcomed onto the team when I first started making contributions, so thank you for that in particular.

**Comment by camelid** [comment]
Thank you for mentoring me as I started contributing and continuing onward, for many fun discussions about how to improve rustdoc, for helping me to learn PR review, and for many other things. It's been a lot of fun the last couple of years!

**Review by rylev — APPROVED** [review]
Thank you!

**Comment by willcrichton** [comment]
Thanks @jyn514!! You're the reason I was able to get --scrape-examples off the ground and on nightly.

**Comment by hi-rustin** [comment]
I have received many comments and help with my PR from you in the past and you are always so patient and enthusiastic. Thank you so much! @jyn514

**Comment by janriemer** [comment]
I remember [my first PR for Rust](https://github.com/rust-lang/rust/pull/75049) where you've responded to my questions so quickly, it was almost scary. :smile: 
Speaking of scary: In the PR there was a situation, [where the *ghost emoji* disappeared by accident](https://github.com/rust-lang/rust/pull/75049#issuecomment-674563242). :ghost: Fortunately, we could add it back in. :relieved: Now, you are leaving the Rustdoc team, but... maybe you will come back in the future, just like the ghost emoji did (at least, that's what I hope)!? :smiling_face_with_tear: 

Thank you, @jyn514, for all you have done for the Rust community and rustdoc. :heart: I wish you all the best on your future journey.

**Pull request merged**
