### PR TITLE
add vincenzopalazzo to async-wg

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
While working with an async-wg for a while, and finding my own way in the  [async roadmap](https://rust-lang.github.io/wg-async/vision/roadmap.html#overview) I would like to add my self inside the team, and work hard to have a long adventure inside the rust team 😸 

Signed-off-by: Vincenzo Palazzo <vincenzopalazzodev@gmail.com>

### CODE REVIEW

**Comment by rylev** [comment]
Pinging @nikomatsakis @tmandry for review.

**Comment by tmandry** [comment]
I synced up with @vincenzopalazzo about this. The WG [membership requirements](https://rust-lang.github.io/wg-async/CHARTER.html#membership-requirements) mention having a track record of contributions before someone is invited onto the team, so I'd like to work with them to build that up first. Overall though, I'd be happy to have them join once that is done!

**Comment by rylev** [comment]
Ok going to close this for now - we can reopen this when everything is ready to go.

**Comment by vincenzopalazzo** [comment]
Spoken with @tmandry for this to reopen the issue

**Review by tmandry — APPROVED** [review]

**Comment by tmandry** [comment]
@rylev can we merge this now?

**Comment by Mark-Simulacrum** [comment]
It looks like the branch here is deleted? But happy to merge a similar PR.

**Comment by vincenzopalazzo** [comment]
@Mark-Simulacrum sorry I do not know how this happens with I open a new one https://github.com/rust-lang/team/pull/991

**Pull request closed without merging**
