### PR TITLE
Add myself & a few others to the WG

### PR DESCRIPTION
**Pull request by zeenix**
As agreed with @tmandry, adding myself, Andrew Chin, Emmanuel Antony and Doc Jones (I hope I got their Github username right) to the team.

cc @nikomatsakis

### CODE REVIEW

**Comment by zeenix** [comment]
@doc-jones, @eminence and @emmanuelantony2000, please let me know if you've any objections on being officially part of the team and I can remove your names from the list. Otherwise, please do give a :+1: to indicate that you're ok with this. Thanks.

**Comment by doc-jones** [comment]
👍

**Comment by eminence** [comment]
👋 👍

**Review by nikomatsakis — DISMISSED** [review]

**Comment by nikomatsakis** [comment]
Yep, approved and welcome! Can someone from @rust-lang/core merge please?

**Review by Manishearth — APPROVED** [review]

**Comment by skade** [comment]
You need to create all the users, they are currently not present.

**Comment by zeenix** [comment]
> You need to create all the users, they are currently not present.

Done.

**Review by skade — APPROVED** [review]
Thanks for fixing!

**Pull request merged**
