### PR TITLE
Update the current embedded WG members list

### PR DESCRIPTION
**Pull request by therealprof**
All inactive/hibernating members are moved to the alumni section to
recognize their contributions.

CC https://github.com/rust-embedded/wg/pull/476

Signed-off-by: Daniel Egger <daniel@eggers-club.de>

### CODE REVIEW

**Comment by pietroalbini** [comment]
We need to change this to avoid including WG alumni to the `all@` mailing list.

**Comment by therealprof** [comment]
> We need to change the team repo to avoid including WG alumni to the `all@` mailing list before merging this PR.

Is that something I can/should do and if so can you give any pointers what you mean by that?

**Comment by pietroalbini** [comment]
The source code of the team repo would need to change.

Unfortunately I don't have much time to provide pointers in the next few days, but I'll get around to do the change soon. If you want to try of course you're free to do so :)

**Comment by therealprof** [comment]
Well, in any case this PR should be good to go because it doesn't make any difference whether the people receive emails to @all due to being on the active members list or on the alumni list. ;)

**Comment by pietroalbini** [comment]
> Well, in any case this PR should be good to go because it doesn't make any difference whether the people receive emails to @ALL due to being on the active members list or on the alumni list. ;)

Well, working groups are not on `all@`.

**Comment by pietroalbini** [comment]
Opened https://github.com/rust-lang/team/pull/380 to remove alumni from `all@`.

**Comment by therealprof** [comment]
Thank you!

**Comment by therealprof** [comment]
BTW: I don't see the update on the website yet, despite this being merged 3 hours ago and the team frontpage claiming it'd be synchronized every 2 minutes.

**Comment by pietroalbini** [comment]
[GitHub is being funky today](https://www.githubstatus.com/incidents/phnch1rww464)

**Comment by pietroalbini** [comment]
The change should be live now.

**Comment by therealprof** [comment]
Yes, confirmed. Thanks!

**Pull request merged**
