### PR TITLE
trans my gender

### PR DESCRIPTION
**Pull request by Noratrieb**
the usual, you should be familiar with this procedure by now.
@pietroalbini told me I should do this as quickly as possible so CI here isn't sad

### CODE REVIEW

**Review by aDotInTheVoid — APPROVED** [review]

**Comment by Noratrieb** [comment]
thanks for validating my gender alona

**Review by jieyouxu — APPROVED** [review]

**Comment by compiler-errors** [comment]
r=me

**Review by ultrabear — APPROVED** [review]
LGTM

**Review by bend-n — APPROVED** [review]

**Review by BoxyUwU — CHANGES_REQUESTED** [review]
What about the discord username?

**Review by WaffleLapkin — APPROVED** [review]
thanks for your contribution 🏳️‍⚧️

**Comment by Noratrieb** [comment]
> What about the discord username?

BOXY

**Review by jackh726 — APPROVED** [review]

**Pull request merged**
