### PR TITLE
Add burakemir to opsem extra people

### PR DESCRIPTION
**Pull request by burakemir**
Hello!

I am interested in following the discussions around Rust operational semantics, including the unsafe fragment, more closely.

- Burak

### CODE REVIEW

**Comment by rylev** [comment]
@burakemir we currently don't allow people who are not a member of any team to be added to the list of extra people, but perhaps we should. 

Thoughts? @Mark-Simulacrum @JakobDegen @RalfJung

**Comment by JakobDegen** [comment]
I don't see why we wouldn't, I suppose. Theres nothing that that role gets you other than pinged when you want to be

**Comment by RalfJung** [comment]
Yes we should allow that. I do assume that being in those extra-group does not grant any of the team permissions (for bors, crater, etc).

**Comment by burakemir** [comment]
Thanks for confirming, I inferred from the CI failure. I don't want to cause anyone extra work and would be happy to keep track by other means than "extra people"

**Comment by jackh726** [comment]
CI should be fixed by #1124, can you rebase?

**Comment by burakemir** [comment]
Done.

**Review by rylev — APPROVED** [review]

**Pull request merged**
