### PR TITLE
agdubs deref

### PR DESCRIPTION
**Pull request by ashleygwilliams**

### CODE REVIEW

**Review by badboy — DISMISSED** [review]
👏👏👏 Thank you, Ashley!

ci failure unrelated. we can fix that in a followup.

**Comment by ashleygwilliams** [comment]
haha @badboy i just pushed a commit to fix it. can't have CI fail on my last commit!!

**Comment by badboy** [comment]
> haha @badboy i just pushed a commit to fix it. can't have CI fail on my last commit!!

fair enough! Thanks for doing that.

**Comment by ashleygwilliams** [comment]
threw it in #796 to keep the PRs cleaner

**Review by Mark-Simulacrum — APPROVED** [review]

**Pull request merged**
