### PR TITLE
Add new marker team for Cloud Compute Program

### PR DESCRIPTION
**Pull request by JoelMarcey**
A dedicated team with access to the cloud desktops associated with the [Cloud Compute Program](https://foundation.rust-lang.org/news/2021-11-16-news-announcing-cloud-compute-initiative/).

### CODE REVIEW

**Comment by JoelMarcey** [comment]
Should we also add a dedicated Zulip group for this as well? (e.g., `[[zulip-groups]]`)

**Comment by JoelMarcey** [comment]
cc @yaahc
cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
I don't think Zulip/GitHub are likely to see much use so I'd not bother configuring those. But they don't hurt either so either way is fine.

For onlookers, this is likely a temporary team - mostly for (very) alpha testing.

Modulo CI seems ok to me.

**Comment by compiler-errors** [comment]
Is this the same thing as what @oli-obk added in team#720 ?

**Comment by oli-obk** [comment]
Yea you should be able to just give individual users the dev-desktop permission, but I also don't mind having a separate team yo add people to

**Comment by compiler-errors** [comment]
Ah, missed the part saying:

```
[permissions]
dev-desktop = true
```

Alright. Sorry for the noise, hehe.

**Comment by JoelMarcey** [comment]
I thought having a specific, explicit team would just make things clearer and cleaner. And particularly easier to add folks and, if we ever need to, remove from just one place.

**Review by Mark-Simulacrum — APPROVED** [review]

**Pull request merged**
