### PR TITLE
Archive wg-wasm

### PR DESCRIPTION
**Pull request by yoshuawuyts**
The Wasm WG has been effectively defunct for nearly five years now, and currently has zero active members. Given its status, we should archive it so we can more accurately communicate the status of the working group.

Once this change goes through, I'll begin reaching out to maintainers so we can also officially shut down the [rustwasm org](https://github.com/rustwasm). This predates the current infra setup, so I'll work with the org admins to make sure projects are either archived, or transferred to trustworthy maintainers.

Thanks!

### CODE REVIEW

**Comment by rylev** [comment]
Typically, the team repo is not the appropriate place for discussing whether a particular action should be taken or not (in this case whether to archive the wg-wasm)- the team repo is just for reflecting decisions made elsewhere. Given that it's not exactly clear who should make this decision, perhaps the right thing to do would be to [open an issue on the Council repo](https://github.com/rust-lang/leadership-council/issues/new/choose). Once a decision has been made there, we can then merge this PR.

**Comment by yoshuawuyts** [comment]
Oh yes, of course - I should have mentioned this - but this was discussed last week in the [launching pad channel on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/384197-t-launching-pad/topic/What.20is.20wg-wasm) with @jamesmunns, the council representative for the launching pad team. Given that we don't have a codified process for how to shut down working groups, he suggested that following the process in https://github.com/rust-lang/team/pull/1391 would probably be enough. And he would make sure to inform the council via Zulip to inform this was the direction we were taking in order to make sure the rest of the council was in the know.

That seemed reasonable to me - given the working group has been effectively defunct for five years, and has no members, making the shutdown official seems like the obvious decision to make. It seemed reasonable to me that we didn't need to ask the rest of the council for permission to archive the working group, but mostly had to make sure that they were informed that this was the direction we were going with this. If there were any issues or concerns, I assumed they'd be raised.

Now, I don't believe this actually ended up being communicated to the rest of the council. So this being perhaps a little unexpected is, well, to be expected. This is definitely not the kind o decision we can move forward with without the council's consent. So if we believe the best way forward is to discuss this in a council meeting: yes, happy to file an issue for that and present. I mainly wanted to make clear that this PR was filed as suggested by council members - and not in any way intended to itself be a device to drive a decision.

**Comment by rylev** [comment]
cc @ehuss on whether he believes this requires discussion from the Council or if the decision has already been made.

**Comment by jamesmunns** [comment]
Noting that this hasn't been discussed formally at a council meeting. I did speak informally + publicly with @yoshuawuyts, and I suggested making this PR, but to leave it open for a reasonable amount of time (1-2w) to allow for objections.

There is a council meeting this week, I can raise the topic there, and I suggest we don't merge this until then.

**Comment by rylev** [comment]
I've converted this to a draft so that we don't accidentally merge it before discussion is allowed to happen.

**Comment by jamesmunns** [comment]
Also noting that I raised this in the Council zulip, but we've not had an official meeting, but also that there hadn't been a comment on this thread yet other than me signalling intent:

https://rust-lang.zulipchat.com/#narrow/stream/392734-council/topic/Signalling.20intent.20to.20archive.20WG-WASM/near/446441515

**Comment by jamesmunns** [comment]
This was discussed and voted on in the [Council Zulip](https://rust-lang.zulipchat.com/#narrow/stream/392734-council/topic/Signalling.20intent.20to.20archive.20WG-WASM/near/448376318), with a consensus of Council members approving the archiving of the WG-WASM team, as it has no members.

Speaking as the T-Launching Pad Council Member, I'd also like to note that although efforts regarding Rust and its support for WASM is no longer taking place in the form of a Working Group, Rust remains committed to supporting WASM as an actively supported platform.

Some working groups are created with a temporary scope so that once the work is completed the group can be spun down. We're happy to report this is the case with wg-wasm. Wasm has been a supported platform for Rust for a long time now and Wasm support for Rust is now maintained and developed by the compiler team. The Wasm Working Group has finished their job and is no longer needed for ongoing Wasm support.

There likely will be a future structure to allow communities such as those previously represented by WG-WASM, and today the wider community of developers targeting WASM with Rust, to have a voice in the Rust project, and I plan to reach out to include folks in these communities in those future structures.

Please feel free to reach out to me personally with any concerns or interests regarding this topic.

Unmarking this as a draft, and approving it.

**Review by rylev — APPROVED** [review]

**Pull request merged**
