### PR TITLE
Add pkg-config repo

### PR DESCRIPTION
**Pull request by rylev**
This adds configuration for the [`pkg-config` repo](https://github.com/rust-lang/pkg-config-rs). This largely mirrors the current config on GitHub with addition of granting the rest of the crate-maintainers team maintainer rights.  

This will also remove @sdroege's maintainer rights which might not be desired. I'll have to add support for adding individuals to repos if that's a requirement here. 

r? @m-ou-se @joshtriplett

### CODE REVIEW

**Comment by m-ou-se** [comment]
> This will also remove @​sdroege's maintainer rights which might not be desired.

Oh, please leave his rights in tact for now. 

@sdroege We can try to take over maintenance if you prefer, but it might not be right away.

**Comment by sdroege** [comment]
Let's keep things as they are for now then, works for me!

**Comment by rylev** [comment]
Sounds great! I'll need to add support for adding individuals to repos. In the meantime, I'll manually add the `crate-maintainers` team to the `pkg-config` repo.

**Comment by sdroege** [comment]
Should I add someone else as owner for pkg-config on crates.io? @joshtriplett, @alexcrichton and I are currently owners.

**Comment by m-ou-se** [comment]
@sdroege If you can add `rust-lang-owner`, that'd be great. :)

**Review by Mark-Simulacrum — APPROVED** [review]
Merging, this will temporarily drop access until we merge the sync team PR in the next few minutes.

**Comment by sdroege** [comment]
> @sdroege If you can add `rust-lang-owner`, that'd be great. :)

Just to make sure, the invite arrived?

**Pull request merged**
