### PR TITLE
Add Caleb as co-lead of rustfmt

### PR DESCRIPTION
**Pull request by Manishearth**
cc @calebcartwright @topecongiro 

We've been unable to reach @topecongiro for a while, and it would be nice if Caleb had all the perms so that he can make progress on https://github.com/rust-lang/rust/issues/82385 . He's been doing a lot of the rustfmt work for quite a while now.

@topecongiro, let me know when you get back and we can discuss this.

r? @rust-lang/devtools

### CODE REVIEW

**Comment by kinnison** [comment]
Caleb will also need to have an email address registered, bsaed on the CI failures.

**Review by killercup — APPROVED** [review]

**Review by Xanewok — APPROVED** [review]

**Comment by calebcartwright** [comment]
> Caleb will also need to have an email address registered, bsaed on the CI failures.

Yup, Manish mentioned this a while back but I never got around to it. Opened #552

**Comment by Manishearth** [comment]
cc @Mark-Simulacrum can you rubber stamp?

**Comment by Mark-Simulacrum** [comment]
It looks like you'll need to rebase or otherwise get the commit bumped for CI to pass here (I guess it runs on the push so open/close didn't help). Otherwise this looks good to me.

**Comment by Manishearth** [comment]
Done

**Review by Mark-Simulacrum — APPROVED** [review]

**Pull request merged**
