### PR TITLE
increase permissions for docs.rs team on our own repos

### PR DESCRIPTION
**Pull request by syphar**
currently I can't merge pull requests any more, I assume because `write` is not enough here?

### CODE REVIEW

**Comment by syphar** [comment]
grafik

from https://github.com/rust-lang/docs.rs/pull/2347#pullrequestreview-1755119105

**Comment by rylev** [comment]
@syphar I believe you should be able to push now? There was a bit set limiting pushing to protected branches to admins and maintainers. I think this might have been a left over from before the repo was maintained by the team repo? We might need to update the `sync-team` project to make sure that this is not set unless the configuration calls for it.

**Comment by syphar** [comment]
Works now, thanks!

**Pull request closed without merging**
