### PR TITLE
Add rfcs repo under automation

### PR DESCRIPTION
**Pull request by Kobzol**
Repo: https://github.com/rust-lang/rfcs

https://hackmd.io/@rust-leadership-council/Bk6ge9Xu6 mentions putting this under team leads, so far I just kept access to the teams that had it before, let me know what is the preferred way.

CC @ehuss

Fixes: https://github.com/rust-lang/team/issues/1096

Extracted from GH:
```
org = "rust-lang"
name = "rfcs"
description = "RFCs for changes to Rust"
bots = []

[access.teams]
infra = "admin"
libs = "write"
libs-api = "write"
release = "write"
rfcbot = "write"
security = "pull"
compiler = "write"
all = "write"
lang = "write"
bots = "write"
core = "admin"

[access.individuals]
alexcrichton = "write"
nikomatsakis = "write"
Dylan-DPC = "write"
joshtriplett = "write"
LawnGnome = "write"
nagisa = "write"
Alexendoo = "write"
pietroalbini = "admin"
technetos = "write"
weihanglo = "write"
RalfJung = "write"
davidtwco = "write"
hi-rustin = "write"
sgrif = "write"
camelid = "write"
lnicola = "write"
Gankra = "write"
flodiebold = "write"
estebank = "write"
SimonSapin = "write"
flaki = "write"
blyxyas = "write"
fmease = "write"
GuillaumeGomez = "write"
saethlin = "write"
rust-highfive = "write"
notriddle = "write"
tmandry = "write"
epage = "write"
compiler-errors = "write"
arlosi = "write"
BoxyUwU = "write"
jsha = "write"
extrawurst = "write"
shepmaster = "admin"
Jarcho = "write"
wezm = "write"
cuviper = "write"
KodrAus = "write"
rylev = "admin"
calebcartwright = "write"
Nilstrieb = "write"
HKalbasi = "write"
Turbo87 = "write"
matthiaskrgr = "write"
llogiq = "write"
sunfishcode = "write"
nnethercote = "write"
sebasmagri = "write"
giraffate = "write"
badboy = "admin"
steffahn = "write"
wesleywiser = "write"
rust-lang-owner = "admin"
Kobzol = "admin"
Aaron1011 = "write"
dtolnay = "write"
JoelMarcey = "write"
spacekookie = "write"
Muscraft = "write"
mariannegoldin = "write"
rust-timer = "write"
Mark-Simulacrum = "admin"
U007D = "write"
clubby789 = "write"
nellshamrell = "write"
carols10cents = "write"
Amanieu = "write"
jtgeibel = "write"
Havvy = "write"
Veykril = "write"
workingjubilee = "write"
Manishearth = "write"
ericseppanen = "write"
the8472 = "write"
xFrednet = "write"
SparrowLii = "write"
JohnTitor = "write"
durin42 = "write"
m-ou-se = "write"
andrewpollack = "write"
WaffleLapkin = "write"
lqd = "write"
est31 = "write"
cramertj = "write"
flip1995 = "write"
shadows-withal = "write"
aliemjay = "write"
lowr = "write"
aDotInTheVoid = "write"
ytmimi = "write"
onur-ozkan = "write"
fee1-dead = "write"
bjorn3 = "write"
jonathanpallant = "write"
JakobDegen = "write"
traviscross = "write"
djc = "write"
sfackler = "write"
mdtro = "write"
Eh2406 = "write"
AngelOnFira = "write"
eddyb = "write"
BurntSushi = "write"
bors = "write"
Nadrieril = "write"
apiraino = "write"
petrochenkov = "write"
Byron = "write"
ChrisDenton = "write"
matthewjasper = "write"
cdmistman = "write"
rami3l = "write"
oli-obk = "write"
tmiasko = "write"
pnkfelix = "write"
b-naber = "write"
CAD97 = "write"
Centri3 = "write"
scottmcm = "write"
nikic = "write"
dswij = "write"
celaus = "write"
chenyukang = "write"
yaahc = "write"
thomcc = "write"
ehuss = "write"
eholk = "write"
cjgillot = "write"
jackh726 = "write"
Nemo157 = "write"
rfcbot = "write"
kennytm = "admin"
adityac8 = "write"
lcnr = "write"
albertlarsan68 = "write"
rbtcollins = "write"
TaKO8Ki = "write"
vertexclique = "write"
mattgathu = "write"
jdno = "admin"
digama0 = "write"
syphar = "write"
michaelwoerister = "write"
rustbot = "write"
spastorino = "write"
bennyvasquez = "write"

[[branch-protections]]
pattern = "master"
ci-checks = []
dismiss-stale-review = false
pr-required = false
review-required = false
```

### CODE REVIEW

**Comment by ehuss** [comment]
> so far I just kept access to the teams that had it before

This doesn't seem to have the same permissions that you posted above, which has `all="write"`? Maybe I'm a little confused.

To me, having all leads + leadership-council seems like the right group. Leads should be responsive enough to merge RFCs when they are ready.

However, I'm a little concerned about the way required-approvals would work. I have forgotten how that works, does it require a reviewer to also have write access, or can it be anyone? I have a slight concern that if it requires another lead to approve, and the lead is the author, then they have to go track down someone from another team (or the leadership-council) to step in and approve it.

I think it is great to make progress and clean up the permissions. Thanks!

**Comment by Kobzol** [comment]
> This doesn't seem to have the same permissions that you posted above, which has all="write"? Maybe I'm a little confused.

To be clear, I kept the accesses that I considered to be "reasonable". I almost always remove `bots`, `security` and all contributors from the access list, since these are just artefacts of how the repository was set up manually before. I considered `all` to be the same.

> However, I'm a little concerned about the way required-approvals would work. I have forgotten how that works, does it require a reviewer to also have write access, or can it be anyone? I have a slight concern that if it requires another lead to approve, and the lead is the author, then they have to go track down someone from another team (or the leadership-council) to step in and approve it.

We can basically have the following three "modes" (everything is related to people/teams that have at least `write` access):
1) Allow pushes to master
2) Require PRs, but don't require approvals
3) Require PRs, and require 1 (or more) approvals from other people

I think that 3) (which is the a common mode in other repos) makes sense here, because team leads and council members usually won't actually be the ones submitting the RFC, and in that case only one approval from council/leads is needed. If someone from council/leads submits a RFC PR, then someone else from council/leads would have to approve it.

We can also use 2), which would mean that if council/leads submits a RFC PR, they can merge it themselves. However, I think that this would not improve the status quo mentioned in the linked issue, since then the PR could be insta-merged by anyone with write access (even by accident) even without any previous approval.

In any case, it's not that anyone can review the PR. Only approvals from people with at least write access "count".

**Comment by ehuss** [comment]
Hm, ok. I think we can try that it out and see how it goes (assuming this is updated to also include more people). I guess I'm not quite understanding why this chose the particular teams that it does. I think it should either include all teams (`all`), or just leads. I'm not sure why it would have some in-between choice of people. Thinking about it more, I would lean towards `all`. I don't think we need to worry too much about people merging things they shouldn't.

The worst problems I've seen is that people merge RFCs but forget to rename the file or update the tracking issue link. Those are usually easily identified and rectified.

(We could add a CI check that prevents merging an unnamed file, or any template metadata that is not correct, but that would require either using merge queues, or a require-ci-passing rule, though that rule would not work well in this repo.)

**Comment by Kobzol** [comment]
> Hm, ok. I think we can try that it out and see how it goes (assuming this is updated to also include more people). I guess I'm not quite understanding why this chose the particular teams that it does. I think it should either include all teams (all), or just leads. I'm not sure why it would have some in-between choice of people. Thinking about it more, I would lean towards all. I don't think we need to worry too much about people merging things they shouldn't.

The choice was my bad on my parts, I don't 100 % understand who should have write access to this repo, so don't think too hard about what I included in the TOML file :) Most of the created `team` PRs for repos are quite straightforward, but for some of them I mostly open them up for discussion, and I just initialize the TOML file with something that remotely makes sense to me, but it might not be reasonable :)

So `write` access for `all` + require at least one approval?

**Comment by ehuss** [comment]
That would be my vote.

**Review by Mark-Simulacrum — APPROVED** [review]

**Pull request merged**
