### PR TITLE
Support ability to manage separate permissions for team leads

### PR DESCRIPTION
**Pull request by calebcartwright**
Refs https://github.com/rust-lang/team/pull/610#issuecomment-950419071

cc @Mark-Simulacrum

### CODE REVIEW

**Comment by pietroalbini** [comment]
Will review this in the coming days.

**Comment by calebcartwright** [comment]
@pietroalbini hate to bump but do you still think you'll have bandwidth to review this?

I realize you're always busy juggling 20 different things so no worries if not. It's still not particularly urgent, though it does remain somewhat of a speedbump/consideration for plans to try to grow the rustfmt team due to certain bors permissions the rustfmt team has in other repos

**Review by pietroalbini — APPROVED** [review]
Sorry for the delay! This PR looks good on the code changes side.

**Comment by pietroalbini** [comment]
@rust-lang/core can I get an approval from you on the permissions changes in this PR?

**Review by badboy — APPROVED** [review]

**Pull request merged**
