### PR TITLE
Add Weihang Lo to the Cargo team

### PR DESCRIPTION
**Pull request by ehuss**
cc @rust-lang/cargo @weihanglo

### CODE REVIEW

**Comment by ehuss** [comment]
I'm not sure, would it make sense to set up the GitHub team to be synced with the definition here?

**Review by rylev — APPROVED** [review]

**Comment by rylev** [comment]
@ehuss I have it on my todo list to do this for all teams where it's not the current case. @pietroalbini had set this up for some teams in the past.

**Comment by camelid** [comment]
I think the

```toml
[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]
```

that's in the team file should mean it's already the case that it's auto-synced?

**Comment by ehuss** [comment]
Oh, indead it is, thanks @camelid!

**Pull request merged**
