### PR TITLE
crates.io: Enable `rustbot`

### PR DESCRIPTION
**Pull request by Turbo87**
Related:

- https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/transferring.20issues.20not.20possible
- https://github.com/rust-lang/crates.io/pull/9557

r? @rust-lang/infra

### CODE REVIEW

**Review by MarcoIeni — APPROVED** [review]
I'm approving since it's a simple pr.
If you think this PR should have been approved by the `team-repo-admins` team instead, please reach out and let's discuss this 👍

**Comment by Turbo87** [comment]
> If you think this PR should have been approved by the `team-repo-admins` team instead, please reach out and let's discuss this

I don't think that's necessary for this PR

**Comment by MarcoIeni** [comment]
I chatted with JD, the general rule is that infra only merge changes to `.rs` files, so I'll wait for the `team-repo-admins` to merge this 👍

**Comment by Turbo87** [comment]
side note: this is a change related to the crates.io repository, which is managed by the crates.io team. why does it need approval from @rust-lang/team-repo-admins? if anything it feels like it would need approval from the @rust-lang/crates-io team instead?

the amount of work, bureaucracy and approvals necessary to get an issue moved is quite staggering...

**Comment by Kobzol** [comment]
This specific change is very unlikely to really *need* approval from team-repo-admins, but in general it's quite hard to design a heuristic for this. Therefore, so far the consensus is that (at least TOML) changes need approval from team-repo-admins. I think that it would be great if we could grow that team though..

**Comment by MarcoIeni** [comment]
I think it's worth discussing this in zulip or in a separate GitHub issue 👍

**Comment by Turbo87** [comment]
@rust-lang/team-repo-admins is anything blocking this from your side? do you need more information? what can I do to speed up this process?

**Comment by ChrisDenton** [comment]
I think most/all of the admins are away atm. Nothing has been merged in a week.

**Review by rylev — APPROVED** [review]

**Pull request merged**
