### PR TITLE
Update rustup.toml

### PR DESCRIPTION
**Pull request by hi-rustin**
I will start a new job recently and I have no time to help the rustup. Hope one day I can come back.

cc: @rbtcollins Thanks for your help!

### CODE REVIEW

**Comment by weihanglo** [comment]
Thank you @hi-rustin! Looking forward to your return :)

**Comment by hi-rustin** [comment]
cc: @rylev 
Could you please take a look? Thanks! 💚 💙 💜 💛 ❤️

**Review by rylev — APPROVED** [review]

**Comment by Rustin170506** [comment]
> Hope one day I can come back.

I've been part of a new team at my job for over a year now and have basically gotten the hang of the job (except oncall 😆) I feel like it's time to return to rustup to help improve it. It seems to be in great shape already! I'll do my best to contribute and make it even better. @rust-lang/rustup Would it be possible to add me back to the team? Thank you so much!

**Comment by rami3l** [comment]
> > Hope one day I can come back.
> 
> I've been part of a new team at my job for over a year now and have basically gotten the hang of the job (except oncall 😆) I feel like it's time to return to rustup to help improve it. It seems to be in great shape already! I'll do my best to contribute and make it even better. @rust-lang/rustup Would it be possible to add me back to the team? Thank you so much!

@Rustin170506 Personally I'd definitely be happy to welcome you back to the team! But maybe in terms of the process, it'd be better if you don't mind drafting a PR and asking for review from @rust-lang/rustup instead?

**Pull request merged**
