### PR TITLE
mod team resignation

### PR DESCRIPTION
**Pull request by BurntSushi**
The entire moderation team resigns, effective immediately. This resignation is
done in protest of the Core Team placing themselves unaccountable to anyone but
themselves.

As a result of such structural unaccountability, we have been unable to enforce
the Rust Code of Conduct to the standards the community expects of us and
to the standards we hold ourselves to. To leave under these circumstances
deeply pains us, and we apologize to all of those that we have let down. In
recognition that we are out of options from the perspective of Rust Governance,
we feel as though we have no course remaining to us but to step down and make
this statement.

In so doing, we would offer a few suggestions to the community writ large:

* We suggest that Rust Team Members come to a consensus on a process for
oversight over the Core Team. Currently, they are answerable only to
themselves, which is a property unique to them in contrast to all other Rust
teams.
* In the interest of not perpetuating unaccountability, we recommend that the
replacement for the Mod Team be made by Rust Team Members not on the Core Team.
* We suggest that the future Mod Team, with advice from Rust Team Members,
proactively decide how best to handle and discover unhealthy conflict among
Rust Team Members. We suggest that the Mod Team work with the Foundation in
obtaining resources for professional mediation.
* Additionally, while not related to this issue, based on our experience in
moderation over the years, we suggest that the future Mod Team take special
care to keep the team of a healthy size and diversity, to the extent possible.
It is a thankless task, and we did not do our best to recruit new members.

In this message, we have avoided airing specific grievances beyond
unaccountability. We've chosen to maintain discretion and confidentiality. We
recommend that the broader Rust community and the future Mod Team exercise
extreme skepticism of any statements by the Core Team (or members thereof)
claiming to illuminate the situation.

We are open to being contacted by Rust Team Members for advice or
clarification.

Sincerely,
The Rust Moderation Team (Andre, Andrew and Matthieu)

### CODE REVIEW

**Comment by matthieu-m** [comment]
I confirm that I am resigning, and that I am co-signing the above PR.

**Comment by llogiq** [comment]
I also confirm that I am resigning and co-signing the PR.

**Comment by Trismegistos84** [comment]
This resignation letter looks like attack on core team not a real resignation.

**Comment by opsxcq** [comment]
I'm a black latino from a 3rd world country, I hereby declare that I'm voluteering for being a mod.

**Comment by jhpratt** [comment]
While I believe that discussion is healthy, I suggest that this PR's discussion be locked to avoid the inevitable mudslinging and low-quality comments.

**Comment by mintsuki** [comment]
Install Gentoo.

**Comment by tymondouglas** [comment]
Great

**Comment by Moe-Szyslak** [comment]
Not sure what this is about but the code LGTM

**Review by magnusja — APPROVED** [review]

**Review by Moe-Szyslak — APPROVED** [review]
LGTM

**Comment by llogiq** [comment]
> This resignation letter looks like attack on core team not a real resignation.

I can assure you the resignation is real. And we have chosen not to name names or divulge specifics that could implicate anyone. Even so, we felt that we should state our reasons for resigning to avoid people making up their own drama.

**Review by aidanhs — APPROVED** [review]

**Comment by khionu** [comment]
We appreciate everyone's concern, however until we can sort things, I would encourage you all to keep discussion on the [Reddit thread](https://www.reddit.com/r/rust/comments/qzme1z/moderation_team_resignation/).

**Pull request merged**
