### PR TITLE
Archive some teams and add alumni

### PR DESCRIPTION
**Pull request by XAMPPRocky**
Archives some of the teams that no longer active.

r? @nikomatsakis

### CODE REVIEW

**Comment by pietroalbini** [comment]
Are we worried about the `ecosystem@` and `production@` mailing lists disappear?

**Comment by Manishearth** [comment]
I don't think they were ever in use? But perhaps we should have a bounces list just in case.

**Comment by XAMPPRocky** [comment]
For future proofing i think we'd want to have a bounces list regardless. As even if they are unused, eventually we'll have one that has been used, that we want to archive.

**Comment by Manishearth** [comment]
Yes, I'm proposing a general bounces list, not one specifically for these :)

**Comment by nikomatsakis** [comment]
Seems good to me. I've got a branch trying to modernize the 'networking working group' setup to reflect the people who are most active now, I've just been debating how precisely to set it up.

**Comment by nikomatsakis** [comment]
I don't quite understand what you all mean by a "bounces" list -- what is that and what should we do to set it up?

**Comment by nikomatsakis** [comment]
Does that block me from merging this PR? :)

**Comment by XAMPPRocky** [comment]
@nikomatsakis An email bounce list, so that any emails sent to the mailing list addresses after the team is removed are sent *somewhere* rather being lost to the ether. I don't what it would take to set that up. I don't know if these email addresses are worth that, as I don't know how active they were. I don't think it should be a blocker for merging.

**Comment by nikomatsakis** [comment]
OK, I'm going to just go ahead and merge this. Based on earlier comments it doesn't sound like anyone objects.

**Pull request merged**
