### PR TITLE
Add myself to libc bors permissions

### PR DESCRIPTION
**Pull request by joshtriplett**

### CODE REVIEW

**Comment by joshtriplett** [comment]
cc @alexcrichton

**Review by alexcrichton — APPROVED** [review]

**Comment by JohnTitor** [comment]
Hm, we currently don't use bors on libc as Alex suggested, do we use it again?

**Comment by joshtriplett** [comment]
Fair enough. I'd like to go ahead and get added in case that changes, but I'm not looking to propose changing that. :)

**Comment by Mark-Simulacrum** [comment]
I am personally against expanding the set of permissions like this for a hypothetical future - that said, it would be great to create a libc team/group (at least marker) rather than managing these permissions per-person.

**Comment by joshtriplett** [comment]
Happy to see this happen via a group instead.

**Pull request closed without merging**
