### PR TITLE
Remove myself from the crates.io team

### PR DESCRIPTION
**Pull request by steveklabnik**
While I do care about policy, and want to help with that in the future, I haven't done any work on crates.io in a long time.

### CODE REVIEW

**Comment by JohnTitor** [comment]
You should add yourself to alumni instead of just removing :) See #412 for example.

**Comment by steveklabnik** [comment]
Sorry for the *very* long wait here, but this should be good now?

**Comment by Manishearth** [comment]
It is, but this repo's CI is broken (not your fault)

**Comment by pietroalbini** [comment]
The PR needed a rebase, as that error is not present on master anymore. Since the PR was correct apart from that, merged it.

**Pull request merged**
