### PR TITLE
add myself to compiler-contributors

### PR DESCRIPTION
**Pull request by RalfJung**
@pietroalbini told me to give myself crater permissions. Looks like being in that team will also do the job, and the team description does apply to me I'd argue. ;)

### CODE REVIEW

**Comment by nikomatsakis** [comment]
Technically, there's a nomination process here. Let me consult with team briefly, though I agree that you'd be a good candidate given your expertise in miri and so forth. =)

**Comment by nikomatsakis** [comment]
Welcome, @RalfJung!

**Comment by RalfJung** [comment]
> Welcome, @RalfJung!

Thanks. :-)

**Pull request merged**
