### PR TITLE
Add mark-i-m as co-lead and remove nikomatakis from learning wg

### PR DESCRIPTION
**Pull request by spastorino**
I'd like to propose @mark-i-m as WG learning co-lead. Mark, please approve if you want to be part of lead group :).

r? @nikomatsakis

### CODE REVIEW

**Comment by nikomatsakis** [comment]
@spastorino I think you can remove me

**Comment by nikomatsakis** [comment]
Also, CI is unhappy? Maybe mark-i-m needs to be added?

**Comment by nikomatsakis** [comment]
r=me once those things are fixed (ping me if needed)

**Comment by spastorino** [comment]
```
ERROR validation error: person `mark-i-m` is a member of a mailing list but has no email address
ERROR 1 validation errors found
```

@mark-i-m needs to add an email address now in https://github.com/rust-lang/team/blob/master/people/mark-i-m.toml

**Comment by spastorino** [comment]
@nikomatsakis I've removed you from the team, unsure if you wanted to stay there and just be removed only from the leads team. My guess was that you prefer to be out of the group and be called if it's needed :).

**Comment by mark-i-m** [comment]
Opened https://github.com/rust-lang/team/pull/173

**Comment by spastorino** [comment]
Added the email here, so it's easier to merge everything at once. @mark-i-m you can close #173

**Pull request merged**
