### PR TITLE
Add myself to community team

### PR DESCRIPTION
**Pull request by JohnTitor**
Discussed with Florian, and I'd like to add myself to the community team.

r? @skade

### CODE REVIEW

**Comment by JohnTitor** [comment]
And we should add `[github] orgs = ["rust-lang"]` to add me to the GitHub team?

**Comment by skade** [comment]
I will need to add you to the community team manually, we don't deploy the org automatically.

**Comment by JohnTitor** [comment]
@skade I would like to also join the event team and localization WG to clarify what I should do. Is that okay? (I think that is the place where I can be active.)

**Comment by JohnTitor** [comment]
And who should I ask to merge?

**Comment by alexcrichton** [comment]
Carrying over @skade's approval to a merge

**Pull request merged**
