### PR TITLE
Add Boqun Feng to opsem meetings ping group

### PR DESCRIPTION
**Pull request by fbq**

### CODE REVIEW

**Comment by rylev** [comment]
r? @JakobDegen or @RalfJung 

In order to merge this we need to change the validation to allow people to only be part of Zulip user groups. Currently CI fails if the person is not a member of a team or has a specific permission.

**Review by RalfJung — DISMISSED** [review]
Always happy to include more interested people here. :)

**Review by RalfJung — APPROVED** [review]
I can't land PRs here, sorry. Definitely approved from my side though!

Anybody is free to add themselves to the "meetings" group.

**Comment by fbq** [comment]
> I can't land PRs here, sorry.

No problem! And kindly ping @rylev ;-)

> Definitely approved from my side though!

Thanks!

> Anybody is free to add themselves to the "meetings" group.

**Comment by rylev** [comment]
This has the same issue as https://github.com/rust-lang/team/pull/1120 - we don't allow people who are not a member of any team to be a part of these groups. I think we'll want to loosen this restriction though. cc @Mark-Simulacrum

**Comment by jackh726** [comment]
CI should be fixed by #1124, can you rebase?

**Comment by fbq** [comment]
> CI should be fixed by #1124, can you rebase?

Thanks! And done

**Review by jackh726 — APPROVED** [review]

**Pull request merged**
