### PR TITLE
Synchronize wg-learning with GitHub teams

### PR DESCRIPTION
**Pull request by spastorino**
Waiting for more members to answer here https://rust-lang.zulipchat.com/#narrow/stream/196385-t-compiler.2Fwg-learning

### CODE REVIEW

**Comment by pietroalbini** [comment]
```
ERROR validation error: person `amanjeev` is member of team `wg-learning` but doesn't exist
ERROR validation error: person `mark-i-am` is member of team `wg-learning` but doesn't exist
ERROR validation error: person `tshepang` is member of team `wg-learning` but doesn't exist
```

You need to run `cargo add-person <name>`.

**Comment by pietroalbini** [comment]
@spastorino are you ok merging this?

**Comment by spastorino** [comment]
@pietroalbini yes, let merge it now!. Missing people that want to be part can be included afterwards.

**Comment by pietroalbini** [comment]
@amanjeev @mark-i-m @tshepang @togiberlin y'all should receive an automatic invite to join the rust-lang org in the next ~10 minutes.

**Comment by mark-i-m** [comment]
I didn't receive an invite, I think, though I already have admin access on the guide repo....

**Comment by pietroalbini** [comment]
@mark-i-m the script should've invited you...

**Comment by pietroalbini** [comment]
@mark-i-m sent a manual invitation again.

**Pull request merged**
