### PR TITLE
 Grant try permissions to Rust for Linux marker team

### PR DESCRIPTION
**Pull request by ojeda**
In order to test changes to the RFL CI job, if needed.

Cc: @Kobzol

### CODE REVIEW

**Comment by Kobzol** [comment]
Maybe we should add the permissions to the whole RfL group? Not sure what's the policy on try permissions for individual users (I'll let others chime in).

**Comment by ojeda** [comment]
If you are comfortable adding all of them, of course! All but 2 of them, I think, are already Rust contributors.

**Comment by joshtriplett** [comment]
:+1: for granting try permissions to the entire RfL team within the teams repo.

**Comment by ojeda** [comment]
Thanks Josh!

Updated PR.

**Review by tmandry — APPROVED** [review]

**Review by joshtriplett — APPROVED** [review]

**Comment by joshtriplett** [comment]
@ojeda You should update the PR title too.

**Review by jackh726 — APPROVED** [review]
Merging with @tmandry's approval here as lang-team lead here - but I think in general this makes a lot of sense.

**Comment by ojeda** [comment]
Thanks Jack!

**Pull request merged**
