### PR TITLE
Add new crate maintainers team.

### PR DESCRIPTION
**Pull request by m-ou-se**
Hey @Amanieu @JohnTitor @KodrAus @joshtriplett @the8472 @thomcc @workingjubilee, does this look right?

### CODE REVIEW

**Review by JohnTitor — APPROVED** [review]
Looks right to me 👍

**Comment by rylev** [comment]
Question to naming: the name "crates" might be a bit confusing when seen without the context of it being a libs subteam. I wonder if there's another name that's just as succinct but less prone to being misunderstood. 

Also, I missed any discussion about why this changed was deemed necessary. If there's any link to such discussion, I would personally find it useful (also for those who stumble upon this PR in the future).

**Comment by JohnTitor** [comment]
> Question to naming: the name "crates" might be a bit confusing when seen without the context of it being a libs subteam. I wonder if there's another name that's just as succinct but less prone to being misunderstood.
> 
> Also, I missed any discussion about why this changed was deemed necessary. If there's any link to such discussion, I would personally find it useful (also for those who stumble upon this PR in the future).

This meeting has related discussion: https://rust-lang.zulipchat.com/#narrow/stream/259402-t-libs.2Fmeetings/topic/Meeting.202022-09-14/near/298789218
And meetings on other dates also have some more discussion, you could search "crates-maintainers" or something else on Zulip.

**Comment by m-ou-se** [comment]
> Question to naming: the name "crates" might be a bit confusing when seen without the context of it being a libs subteam. I wonder if there's another name that's just as succinct but less prone to being misunderstood.

"team responsible for maintaining the crates that are maintained by the rust team but are not the standard library" is a bit long, but I'm not sure what's the best way to shorten it. Suggestions welcome. :)

**Comment by m-ou-se** [comment]
@rylev This is ready for merging, except for the team name bikeshed.

`crate-maintainers`? `libs-crate-maintainers`? `official-but-not-quite-standard-crates-maintainers`? `log-libc-compiler-builtins-etc-etc-etc-maintainers`? `naming-is-hard`? Very open for better suggestions. ^^'

**Comment by rylev** [comment]
I think `crate-maintainers` is probably fine. I'll leave this open for a little while longer to see if any other opinions come in for names, but then we can merge this.

**Comment by weihanglo** [comment]
The description of Library team says

> Managing and maintaining the Rust standard library and official rust-lang crates.

Since it is a subteam of libs team, it is very clear to me that it maintains official rust-lang crates. At least as an outsider :)

Though I am more curious about how one knows which crate is maintained by this team?

**Review by rylev — APPROVED** [review]
I'll merge this now. 

@m-ou-se does it make sense to add a Zulip user group for pinging these folks or is it too much of a catch-all for that to be useful?

**Comment by m-ou-se** [comment]
@rylev Yes. Is that something that can happen automatically now? Or do we need to manually create that in Zulip?

**Comment by m-ou-se** [comment]
@pietroalbini can you give this new `crate-maintainers` group GitHub write and Crates.io publish access to `libc`, `compiler-builtins`, `libm`, `log`, `libz-sys`, `cfg-if`, `cc`, `cmake`, `pkg-config`, `glob`, `flate2`, `socket2`, `getopts`, and `backtrace-rs`?

**Comment by rylev** [comment]
Oh I would love to do this through the repo configuration option in the team repo (since we have to do that eventually anyhow). How urgent is this? (i.e., if it takes a day or two is that fine?)

**Comment by m-ou-se** [comment]
@rylev It'd be nice to fix it for `libc` right now, because the old libc team was removed by this PR. For the rest, a few days delay is fine. :)

**Comment by rylev** [comment]
@m-ou-se FYI: `sync-team` does not yet *delete* GitHub teams that are defined on GitHub but not in the team repo (though I'd like to add that very soon). In any case, I've added the new team to the `libc` repo anyway.

**Comment by thomcc** [comment]
In https://github.com/rust-lang/cc-rs/pull/661#issuecomment-1290945160 I realized I don't seem to have the ability to merge PRs in `cc`, should I? I do for some of the other crates.

**Comment by rylev** [comment]
@thomcc I've added `crate-maintainers` to the `cc-rs` repo so you should be good to go.

**Comment by thomcc** [comment]
@rylev I promised I'd cut a release of `cmake-rs` in https://github.com/rust-lang/cmake-rs/issues/162#issuecomment-1292171600, but after doing a review I realize it doesn't seem like I have access to that either.

Can you double-check versus the list @m-ou-se gave in [this comment](https://github.com/rust-lang/team/pull/861#issuecomment-1286670330)?

**Comment by thomcc** [comment]
(Oh, sorry, this is being done in https://github.com/rust-lang/team/pull/879, my bad!)

**Pull request merged**
