### PR TITLE
Add kupiakos.toml, add to wg-binary-size

### PR DESCRIPTION
**Pull request by kupiakos**
See https://github.com/rust-lang/wg-binary-size/issues/4. I've already talked with @tgross35

### CODE REVIEW

**Comment by kupiakos** [comment]
Oh yes, my apologies, that is who I meant. I had used your PR to join as a template which he had linked and I had confused for his own.

**Review by thomcc — APPROVED** [review]
Sorry for the delay, I've been away on vacation for the past 3 weeks.

This looks fine.

**Comment by Kobzol** [comment]
CC @jackh726 (I saw you approve a newer PR, so not sure if you got the notif. that this was approved by thomcc :) ).

**Review by rylev — APPROVED** [review]

**Pull request merged**
