### PR TITLE
Add `@aDotInTheVoid` in the rustdoc team

### PR DESCRIPTION
**Pull request by GuillaumeGomez**
Welcome to the team! :partying_face: 

cc @aDotInTheVoid @rust-lang/rustdoc

### CODE REVIEW

**Comment by jsha** [comment]
Welcome to the team, @aDotInTheVoid! Glad to have you.

**Review by Manishearth — APPROVED** [review]
Welcome!

**Comment by aDotInTheVoid** [comment]
Thanks

**Review by aDotInTheVoid — APPROVED** [review]

**Comment by camelid** [comment]
Welcome @aDotInTheVoid!

**Review by Mark-Simulacrum — APPROVED** [review]

**Pull request merged**
