### PR TITLE
Add @blyxyas and @Centri3 to the Clippy Team :tada: :confetti_ball: :paperclips: 

### PR DESCRIPTION
**Pull request by xFrednet**
:drum: :drum: :drum: 

Welcome to the Clippy Team @blyxyas and @Centri3 :tada: :confetti_ball: :paperclips: 

---

@Centri3 Could you give me an email for your user file? The README includes a section on [how to encrypt it](https://github.com/rust-lang/team#encrypting-email-addresses), if you don't want it to be public :)

Once this PR is done, I'll also add you two to the reviewer rotation in the Clippy repo. Thank you for all the work you have already done in the past few months! :heart:

---

r? @flip1995 || @Manishearth 

cc: @rust-lang/clippy

### CODE REVIEW

**Review by flip1995 — APPROVED** [review]
Welcome to the team to both of you! Looking forward to your future contributions.

(approval pending email address)

**Comment by Centri3** [comment]
> (approval pending email address)

I've already sent it to xfrednet, it's `catherine3.flores@gmail.com`. Waiting on him to update it now, forgot to create an alias sooner :sweat_smile:

**Comment by blyxyas** [comment]
Flores? @Centri3 are you from a spanish-speaking place? That'd be so epic ^w^

**Comment by Centri3** [comment]
Sorry to disappoint, but that's just my last name ^^

**Comment by xFrednet** [comment]
Thank you! I've fixed up the last commit with your email. Now everything should be ready :rocket: 

r? @Mark-Simulacrum

**Review by Manishearth — APPROVED** [review]
welcome to the team!

**Review by rylev — APPROVED** [review]

**Pull request merged**
