### PR TITLE
Add a batch of 4 repositories for archival #3

### PR DESCRIPTION
**Pull request by Kobzol**
**These repositories are not yet archived!**

Repositories were selected based on https://hackmd.io/@rust-leadership-council/Bk6ge9Xu6 and usage statistics.

- https://github.com/rust-lang/project-rfc-2229
<details>
<summary>Extracted from GH</summary>

```toml
org = "rust-lang"
name = "project-rfc-2229"
description = "A repository tracking the planning for implementation and evaluation of RFC 2229."
bots = []

[access.teams]
compiler-contributors = "write"
compiler = "write"
security = "pull"
wg-rfc-2229 = "write"

[access.individuals]
est31 = "write"
the8472 = "write"
Azhng = "write"
oli-obk = "write"
wesleywiser = "write"
davidtwco = "write"
pietroalbini = "admin"
saethlin = "write"
Nilstrieb = "write"
chenyukang = "write"
nagisa = "write"
tmiasko = "write"
b-naber = "write"
fmease = "write"
petrochenkov = "write"
nnethercote = "write"
logmosier = "write"
cuviper = "write"
durin42 = "write"
ChrisPardy = "write"
nikomatsakis = "write"
lcnr = "write"
spastorino = "write"
WaffleLapkin = "write"
lqd = "write"
cjgillot = "write"
fee1-dead = "write"
bjorn3 = "write"
rust-lang-owner = "admin"
Mark-Simulacrum = "admin"
michaelwoerister = "write"
RalfJung = "write"
eddyb = "write"
flodiebold = "write"
tmandry = "write"
jackh726 = "write"
jdno = "admin"
SparrowLii = "write"
nikic = "write"
estebank = "write"
badboy = "admin"
apiraino = "write"
pnkfelix = "write"
eholk = "write"
BoxyUwU = "write"
TaKO8Ki = "write"
rylev = "admin"
Nadrieril = "write"
roxelo = "write"
null-sleep = "write"
Aaron1011 = "write"
compiler-errors = "write"
jenniferwills = "write"
matthewjasper = "write"
arora-aman = "write"

```

</details>

- https://github.com/rust-lang/rfc-leadership-council
<details>
<summary>Extracted from GH</summary>

```toml
org = "rust-lang"
name = "rfc-leadership-council"
description = "RFCs for changes to Rust"
bots = []

[access.teams]
security = "pull"

[access.individuals]
joshtriplett = "admin"
jdno = "admin"
Mark-Simulacrum = "admin"
khionu = "admin"
rylev = "admin"
badboy = "admin"
rust-lang-owner = "admin"
pietroalbini = "admin"
technetos = "admin"
yaahc = "admin"

```

</details>

- https://github.com/rust-lang/rust-marketing
<details>
<summary>Extracted from GH</summary>

```toml
org = "rust-lang"
name = "rust-marketing"
description = "Rust marketing handbook"
bots = []

[access.teams]
security = "pull"

[access.individuals]
rust-lang-owner = "admin"
Mark-Simulacrum = "admin"
jdno = "admin"
rylev = "admin"
badboy = "admin"
pietroalbini = "admin"

```

</details>

- https://github.com/rust-lang/rust-memory-model
<details>
<summary>Extracted from GH</summary>

```toml
org = "rust-lang"
name = "rust-memory-model"
description = "Collecting examples and information to help design a memory model for Rust."
bots = []

[access.teams]
compiler = "pull"
security = "pull"
core = "pull"

[access.individuals]
eternaleye = "write"
nikomatsakis = "write"
rust-lang-owner = "admin"
badboy = "admin"
rylev = "admin"
pietroalbini = "admin"
strega-nil = "write"
RalfJung = "write"
jdno = "admin"
arielb1 = "write"
Mark-Simulacrum = "admin"

```

</details>

### CODE REVIEW

**Comment by ehuss** [comment]
I'm guessing pentest-2019 is also private.

For rust-memory-model, cc @RalfJung FYI in case you want to keep it open.

**Comment by Kobzol** [comment]
> I'm guessing pentest-2019 is also private.

Damn, I should have checked the lock next to the repo, seems like I have access to too many repositories xD Thanks! Removed it from this PR.

**Comment by RalfJung** [comment]
> rust-memory-model

This one cam be archived, I went over all the issues and moved the relevant to UVG a long time ago.

**Comment by rylev** [comment]
cc @arora-aman and @nikomatsakis re: [project-rfc-2229](https://github.com/rust-lang/project-rfc-2229)

**Review by rylev — APPROVED** [review]

**Pull request merged**
