### PR TITLE
Community team updates

### PR DESCRIPTION
**Pull request by fmoko**
- Remove Ashley from team and team lead positions
- Add fmoko to RustBridge email list

Hopefully this doesn't clash with the other comm team PRs... also @ashleygwilliams can you approve this? I'm not sure whether you've officially left the team completely.

### CODE REVIEW

**Comment by skade** [comment]
If I had a vote, I'd love to keep @ashleygwilliams even just for the regular advice that is still given. I think it makes sense to document the team as leaderless, though I'm still not sure if that's by choice?

**Comment by fmoko** [comment]
@skade it's what I assume to be the popular consensus in the team? If not we can mark it as leaderless for now and elect (even if only nominally) leaders in the next meeting.

**Comment by fmoko** [comment]
Updated this PR with regards to https://github.com/rust-lang/team/issues/146

**Comment by JohnTitor** [comment]
Should we also add the wg-localization?

**Comment by fmoko** [comment]
@JohnTitor Let's do that in a separate PR.

**Comment by JohnTitor** [comment]
Upstream is updated so the CI should be green now.

**Comment by ashleygwilliams** [comment]
i've approved, i'm always around to ask questions,  but it's true im not really an active team member! thanks for doing  this @fmoko

**Comment by fmoko** [comment]
can someone from @rust-lang/core merge this, then?

**Comment by ashleygwilliams** [comment]
merged

**Pull request merged**
