### PR TITLE
chore: archive crates-io-infra repository

### PR DESCRIPTION
**Pull request by MarcoIeni**
I found [this](https://github.com/rust-lang/crates.io-infra) old private repo that seems empty. Should we delete this file and archive the repo?

### CODE REVIEW

**Comment by ehuss** [comment]
Would it make sense to move it to the archive directory and have sync-team handle making it archived?

**Comment by MarcoIeni** [comment]
Archiving the repo was what I wanted to do, I didn't know we had an archive directory 😅 

I moved the file to the `archive` repo 👍

**Review by rylev — APPROVED** [review]

**Comment by jackh726** [comment]
Per archiving policy, team access here should have been removed.

**Comment by MarcoIeni** [comment]
Ooops,

fix: https://github.com/rust-lang/team/pull/1526

I added a validation rule: https://github.com/rust-lang/team/pull/1527 to be merged after the fix PR 👍

**Comment by Kobzol** [comment]
Remark: this repository is private, so after removing all access to it was removed, it is now essentially hidden from the world (maybe just the infra-admins see it). Not sure if that's a problem or not, just wanted to let it be known.

**Comment by MarcoIeni** [comment]
As an infra-admin, I can see it 👍

> Not sure if that's a problem or not, just wanted to let it be known.

I don't know either, if it's a problem for someone, we can discuss it 👍

Btw for context, this repo just had a readme with two lines.

**Pull request merged**
