### PR TITLE
Add spec subteam.

### PR DESCRIPTION
**Pull request by m-ou-se**
This adds the new spec team. See https://github.com/rust-lang/blog.rust-lang.org/pull/1166

### CODE REVIEW

**Comment by nikomatsakis** [comment]
I am comfortable with the name @m-ou-se

**Comment by m-ou-se** [comment]
This is ready for merging now.

**Comment by m-ou-se** [comment]
@rust-lang/lang Your approval is needed to create this subteam. :)

**Comment by nikomatsakis** [comment]
Approved! I am on phone so can't do the GH UI thing just now.

**Review by tmandry — APPROVED** [review]

**Review by Mark-Simulacrum — APPROVED** [review]

**Pull request merged**
