### PR TITLE
Remove lenary from RISC-V

### PR DESCRIPTION
**Pull request by lenary**
I no longer work on the RISC-V LLVM target, and I cannot help to triage RISC-V issues any longer.

### CODE REVIEW

**Comment by camelid** [comment]
I don't think you need to remove your `people/` file; you may join other teams in the future.

**Comment by LeSeulArtichaut** [comment]
> I don't think you need to remove your `people/` file; you may join other teams in the future.

No, it looks like you can't have that: https://github.com/rust-lang/team/blob/420979ae2ebed613f6c7955e90891a8ea9a82dc9/src/validate.rs#L186-L187

**Comment by camelid** [comment]
Scratch that then. Sorry about that!

**Comment by lenary** [comment]
Yeah, I only force-pushed because I got a build failure.

**Pull request merged**
