### PR TITLE
Add a batch of 3 repositories for archival

### PR DESCRIPTION
**Pull request by Kobzol**
**These repositories are not yet archived!**

I added them for archivation based on https://hackmd.io/@rust-leadership-council/Bk6ge9Xu6 and/or what I thought was an obsolete repository.

- https://github.com/rust-lang/atom-ide-rust
<details>
<summary>Extracted from GH</summary>

```toml
org = "rust-lang"
name = "atom-ide-rust"
description = "Rust IDE support for Atom, powered by the Rust Analyzer or Rust Language Server"
bots = []

[access.teams]
security = "pull"

[access.individuals]
jdno = "admin"
rust-lang-owner = "admin"
Mark-Simulacrum = "admin"
aergonaut = "write"
mehcode = "write"
alexheretic = "write"
badboy = "admin"
pietroalbini = "admin"
rylev = "admin"
aminya = "maintain"

```

</details>

- https://github.com/rust-lang/foundation-faq-2020
<details>
<summary>Extracted from GH</summary>

```toml
org = "rust-lang"
name = "foundation-faq-2020"
description = "Have questions on the Rust Foundation? Ask here!"
bots = []

[access.teams]
security = "pull"
core = "admin"
all = "pull"

[access.individuals]
rust-lang-owner = "admin"
badboy = "admin"
jdno = "admin"
rylev = "admin"
pietroalbini = "admin"
Mark-Simulacrum = "admin"

```

</details>

- https://github.com/rust-lang/ghost-code-initiative
<details>
<summary>Extracted from GH</summary>

```toml
org = "rust-lang"
name = "ghost-code-initiative"
description = ""
bots = []

[access.teams]
security = "pull"
lang = "maintain"

[access.individuals]
scottmcm = "maintain"
badboy = "admin"
joshtriplett = "maintain"
jdno = "admin"
rylev = "admin"
pietroalbini = "admin"
Mark-Simulacrum = "admin"
rust-lang-owner = "admin"
nikomatsakis = "maintain"
pnkfelix = "maintain"
tmandry = "maintain"

```

</details>

### CODE REVIEW

**Comment by ehuss** [comment]
Is crates.io-infra a private repo? I can't see it.

I'm actually not certain of the datafrog repo. I would check with @nikomatsakis or @lqd to see what they want to do with it.

I also don't know what ghost-code-initiative is. It looks like something created by @Mark-Simulacrum.

**Comment by Kobzol** [comment]
> Is crates.io-infra a private repo? I can't see it.

Ooh, good point, I haven't realized it, since I can actually access it as a member of `t-infra`. I will remove it, since we don't really support private repositories at the moment (or rather, we do, but we don't manage them, so I don't want to add this as a precedent).

**Comment by lqd** [comment]
If possible I’d prefer not to archive datafrog for now, as we work on alternatives. We may want to merge PRs and do releases until that happens.

**Comment by Kobzol** [comment]
Ok, removed the private repo and `datafrog` from this PR.

**Comment by rylev** [comment]
@Kobzol looks like we can either wait for @Mark-Simulacrum on what the ghost-code-initiative is or we remove it, and we can merge this. I'll leave that up to you.

**Comment by Kobzol** [comment]
Unless it's some top secret project, I assume it's headed for archival. But there's no rush, so let's wait for Mark's response.

**Comment by Mark-Simulacrum** [comment]
I think it's a lang team initiative that I've not heard anything about for a while. Archiving seems safe.

**Review by Mark-Simulacrum — APPROVED** [review]

**Pull request merged**
