### PR TITLE
src: fix include-project-group-leads = true not working

### PR DESCRIPTION
**Pull request by pietroalbini**
Discovered this while looking through the source code.

### CODE REVIEW

**Comment by Mark-Simulacrum** [comment]
This will update the inside rust reviewers marker team and wg-leads. I think I would not want wg-leads to include *project* groups - maybe we should drop it from there before merging this.

**Comment by pietroalbini** [comment]
Hmm, why do you think so? The `if` I changed only gates the execution of the `for` loop, but whether to add team leads or not is decided by the `match` below it.

**Comment by Mark-Simulacrum** [comment]
I mean that we include-project-group-leads is explicitly present in those files: https://github.com/rust-lang/team/blob/master/teams/wg-leads.toml#L8 and https://github.com/rust-lang/team/blob/master/teams/inside-rust-reviewers.toml#L8. The latter makes sense to me, the first seems unexpected.

**Comment by pietroalbini** [comment]
Ok, but this PR doesn't change that. The `include-project-group-leads = true` in those files was already working, as there was another `include-*` matched by the if statement. This PR only fixes `include-project-group-leads = true` not working when there is not any other `include-*.

**Comment by Mark-Simulacrum** [comment]
Right, that makes sense, I misread this PR. Ok, this seems fine to me to merge - it does seem like we could also just get rid of this if entirely and that would maybe be better in some sense.

**Comment by pietroalbini** [comment]
Yeah I totally agree it's confusing. I'll refactor the code in a bit.

**Comment by pietroalbini** [comment]
@Mark-Simulacrum tried pushing a refactoring that should hopefully make this more clear.

**Pull request merged**
