### PR TITLE
Add zulip-groups to rustc-dev-guide team

### PR DESCRIPTION
**Pull request by spastorino**
We would need to check that all of us still want to belong to the team and add each one's zulip-ids. Can you guys please confirm by clicking your box and answering with your zulip-id, so I can fill it in the PR?.

Check https://github.com/rust-lang/team/issues/826 for instructions

cc

* [x]  @amanjeev
* [x]  @togiberlin
* [x]  @JohnTitor
* [x]  @chrissimpkins
* [x]  @camelid
* [x]  @igaray
* [x]  @pierwill
* [x]  @tshepang

### CODE REVIEW

**Comment by tshepang** [comment]
119529

**Comment by pierwill** [comment]
316352

**Comment by JohnTitor** [comment]
My ID will be added by https://github.com/rust-lang/team/pull/805.

**Comment by igaray** [comment]
209053

**Comment by chrissimpkins** [comment]
I appreciate the opportunity to have been part of this rust-lang team.  Due to other commitments, I won't be able to participate further.  It is ok to remove me from the team list.

Thank you!

**Comment by camelid** [comment]
I would like to continue as part of the team! My Zulip ID is already in the teams repo though.

**Comment by spastorino** [comment]
Great, let's wait for the last answer from @togiberlin before pushing the final PR.

**Comment by spastorino** [comment]
I've removed @togiberlin from the group as a way to move this forward. Please feel free to open a PR adding your zulip-id and joining the team again if you want to be included.

**Review by Mark-Simulacrum — APPROVED** [review]

**Pull request merged**
