### PR TITLE
Update username

### PR DESCRIPTION
**Pull request by carols10cents**
r? @skade

### CODE REVIEW

**Comment by skade** [comment]
r+ @carols10cents

**Comment by fmoko** [comment]
does this automatically add me to the org?

**Comment by pietroalbini** [comment]
No because those teams aren't synchronized with GitHub yet.

**Comment by fmoko** [comment]
got it. @skade @carols10cents can one of you invite me and add me to the 'rustlings' team?

**Comment by carols10cents** [comment]
@fmoko done!

**Pull request merged**
